-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgJtxYWpwq4nDNRQF0
jPZIpaXyXvhniK460fCuCes7YT6gCgYIKoZIzj0DAQehRANCAARtfXPVFP9uqQlP
jpndvyUd3K8OM4Uv1Wu77JhpZpC5EXMbpeHTlrPQzjXhbHg/Dqw64kcOBmfKHbwD
FYBwv4d9
-----END PRIVATE KEY-----